name: Mobile e2e tests
on:
  workflow_dispatch:
jobs:
  mobile-e2e-tests:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: 🔨 Build project
        run: npm run build:cap

      - name: 🔨 Build app for iOS simulator
        run: xcodebuild -showsdks
        #xcodebuild -workspace ios/App/App.xcworkspace -scheme App -configuration Debug -sdk iphonesimulator17.5 CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

#      - name: 🏃🏼 Run tests for iOS simulator
#        run: